version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
      - ../data:/app/data
    env_file:
      - .env
    # FastAPI entegrasyonu
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true # Next.js için Docker'da Hot-reload izleme desteği
